version: "3.9"
services:
  api:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - gmail_creds:/data
    restart: unless-stopped
  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
volumes:
  gmail_creds:
